// <auto-generated />
using System;
using HuyHieuDang.Infrastructure.Facades.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HuyHieuDang.Migrators.PostgreSql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919131109_HuyHieuDangBusinessSchema")]
    partial class HuyHieuDangBusinessSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.ModelPermission", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelType")
                        .HasColumnType("text");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("text");

                    b.HasKey("ModelId", "ModelType", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("model_permission", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.ModelRole", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelType")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("ModelId", "ModelType", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("model_role", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Guards")
                        .HasColumnType("text");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Guards")
                        .HasColumnType("text");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("text");

                    b.HasKey("RoleId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Modules.AppSettings.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndYears")
                        .HasColumnType("integer");

                    b.Property<int>("StartYears")
                        .HasColumnType("integer");

                    b.Property<int>("StepYears")
                        .HasColumnType("integer");

                    b.Property<string>("UnitName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("app_setting", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Modules.Auth.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_refresh_token", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Modules.AwardPeriods.Entities.AwardPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromDay")
                        .HasColumnType("integer");

                    b.Property<int>("FromMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("ToDay")
                        .HasColumnType("integer");

                    b.Property<int>("ToMonth")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("award_period", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Modules.PartyMembers.Entities.PartyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("vi-x-icu");

                    b.Property<byte?>("Gender")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("OfficialAdmissionDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OfficialAdmissionDate");

                    b.ToTable("party_member", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Modules.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DayOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("citext");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.ModelPermission", b =>
                {
                    b.HasOne("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.Permission", "Permission")
                        .WithMany("ModelPermissions")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.ModelRole", b =>
                {
                    b.HasOne("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.Role", "Role")
                        .WithMany("ModelRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.RolePermission", b =>
                {
                    b.HasOne("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Modules.Auth.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("HuyHieuDang.Infrastructure.Modules.Users.Entities.User", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Modules.Users.Entities.User", b =>
                {
                    b.HasOne("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.Permission", b =>
                {
                    b.Navigation("ModelPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Facades.Identity.GrantPermission.Entities.Role", b =>
                {
                    b.Navigation("ModelRoles");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("HuyHieuDang.Infrastructure.Modules.Users.Entities.User", b =>
                {
                    b.Navigation("UserRefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
